[build]
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configuración para funciones serverless
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
